### ISSUE TITLE
broken link to provider

### ISSUE THREAD

**Issue by crunchy-vonage** [pactflow/example-bdc-consumer-cypress#10]
On doc page: https://docs.pactflow.io/docs/examples/bi-directional/consumer/cypress/

Broken link:
[Provider](https://github.com/pactflow/example-pactflow-example-provider-dredd)

**Comment by YOU54F** [comment]
Thanks @crunchy-vonage 

This actually affected all of our consumer examples on the docs.pactflow.io site, so really pleased you raised this.

The changes should be live in production in the next 5 minutes!

**Comment by YOU54F** [comment]
Live now buddy thanks 🎉
